name: CI/CD - Build & Push Docker + Update Infra

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/xops-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/xops-app:${{ github.sha }}

      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          repository: YOUR_GITHUB_USER/infra-repo
          token: ${{ secrets.GH_TOKEN }}
          path: infra-repo

      - name: Update deployment.yaml in infra repo
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/xops-app:${{ github.sha }}|" infra-repo/k8s/deployment.yaml
          cd infra-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push
